### ISSUE TITLE
importing cyt.dat during installation yields a long list of errors and warnings

### ISSUE THREAD

**Issue by edwinvdtak-private** [pa3hcm/clog#2]
Hello Maintainer(s),

After some substantial encouragements from Adriaan (PA0RDA) i finally decided to give clog a try. During installation all went pretty smoothly until i got up to the cty.dat "re"-loading part. no serious situation here , bailouts or @INC issues. Just a line at the end yielding "loaded 0 DXCC's and 6379 prefices" I will add the full log as an attachment and hope this is a minor issue.  if you need some help fixing or testing let me know, my email is on qrz.com.  

Thank you for all your efforts to make ham radio a great hobby ! 73 .. 

Edwin/PD0SOT 

[clog-202302161107-termlog.txt](https://github.com/pa3hcm/clog/files/10754706/clog-202302161107-termlog.txt)

**Comment by pa3hcm** [comment]
Was able to reproduce this issue using this setup on Ubuntu Server 22.04.3 LTS with these extra packages installed:

- libswitch-perl 2.17-2.1
- libdbi-perl:amd64 1.643-3build3
- libdbd-mysql-perl:amd64 4.050-5ubuntu0.22.04.1
- mysql-server 8.0.35-0ubuntu0.22.04.1

**Comment by pa3hcm** [comment]
So `gmt_offset` column is `varchar(5)`, fixed the error by increasing it to `varchar(6)`.
